# Generated by Django 4.2.30 on 2026-04-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('info', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('first_aider', models.BooleanField(default=False)),
                ('cscs_card', models.BooleanField(default=False)),
                ('Fire_Marshall', models.BooleanField(default=False)),
                ('driving_license', models.BooleanField(default=False)),
                ('licenseType', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('zipCode', models.CharField(max_length=500)),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(blank=True, max_length=500, null=True)),
                ('additionalInfo', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_aider', models.CharField(max_length=100)),
                ('cscs_card', models.CharField(max_length=100)),
                ('Fire_Marshall', models.CharField(max_length=100)),
                ('driving_license', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
